site_name: 'IGV Documentation'

theme: 
  name: 'windmill'
  custom_dir: custom
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

nav:
- Documentation Home: index.md

- IGV Desktop Application:
    - User Guide: IGV-desktop/IGV_UserGuide.md
    - Release Notes: IGV-desktop/IGV_release_notes.md
        
- IGV-Web App:
    - User Guide: IGV-Web/IGV-Web_UserGuide.md
    
- igv.js:
    - Developer Guide: 
        - IGV Browser Object: igv.js/IGVBrowserObject.md
        - Browser API: igv.js/BrowserAPI.md
        - Tracks: igv.js/Tracks.md
        
- Data Formats: data_formats.md
- Hosting Genomes: hosting_genomes.md
- igv.org: 'https://www.igv.org'
  

markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: 'Direct link to this section'
  - extra
  - sane_lists
  - wikilinks
  - admonition

extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: false
