site_name: 'IGV Documentation'

theme: 
  name: 'windmill'
  custom_dir: custom
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

nav:
- Documentation Home: index.md
- IGV Home page: 'https://www.igv.org'
- FAQ: faq.md
- User Guide:
    - Command Line Options: command_line.md
    - Batch and Port Commands: batch_commands.md
    - RNA Structure: rna_structure.md
- Data Formats: data_formats.md
- Tutorial: tutorial.md
- Misc:
    - Hosting Genomes: hosting_genomes.md
- Help:
  - IGV Help: help/igv_help.md
- Release Notes:
  - IGV Desktop  Release Notes:
    - IGV Desktop 2.9.x: release_notes/igv_desktop/IGV_2.9.x.md
  - igv.js Release Notes: release_notes/igv_js/igv.js_changelog.md

markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: 'Direct link to this section'
  - extra
  - sane_lists
  - wikilinks

extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: false
