site_name: 'IGV Documentation'

theme: 
  name: 'windmill'
  custom_dir: custom
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

nav:
- Documentation Home: index.md
- Navigation: navigation.md
- Multilocus: multi_locus.md
- Regions of Interest: roi.md
- Sessions: sessions.md
- Sample Information: sample_attributes.md
- Tracks:
    - Sequence: tracks/sequence.md
    - Annotations: tracks/annotations.md
    - Alignments:
        - Viewing Alignments: tracks/alignments/viewing_alignments.md
        - Insert Size: tracks/alignments/insert_size.md
        - Pair Orientation: tracks/alignments/pair_orientation.md
        - Bisulfite Sequencing: tracks/alignments/bisulfite.md
        - Base Modifications: tracks/alignments/5mc.md
        - Splice Junctions: tracks/alignments/splice_junctions.md
        - Sashimi Plot: tracks/alignments/sashimi.md
    - Variants (VCF): tracks/vcf.md
    - Mutations (MAF) : tracks/maf.md
    - Segmented Copy Number: tracks/seg.md
    - GWAS: tracks/gwas.md
    - RNA Structure: tracks/rna_structure.md
- Tools:
    - Batch Scripting: tools/batch.md
    - BLAT: tools/blat.md
    - IGV Tools: tools/igvtools_ui.md
    - Motif Finder: tools/motif_finder.md
- Advanced:
  - Authentication: advanced/oauth.md
  - Command Line: advanced/command_line.md
  - Hosting Genomes: advanced/hosting_genomes.md
  - Port Commands: advanced/port.md
  - HTML Links: advanced/links.md
  - Command Line: command_line.md
  - IGV Tools: tools/igvtools_cl.md
- File Formats:
  - Track Line: files/track_line.md
  - Sample Info: sample_info.md
- Release Notes: release_notes.md


markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: 'Direct link to this section'
  - extra
  - sane_lists
  - wikilinks
  - admonition

extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: false
