site_name: 'IGV Desktop Application'

theme: 
  name: 'windmill'
  custom_dir: custom
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

nav:

- IGV Desktop Application: index.md

- User Guide: 
    - IGV basics: UserGuide/IGVbasics.md
    - Reference genome: UserGuide/reference_genome.md
    - Tracks and Data Types:
        - Numeric data: UserGuide/tracks/numeric_data.md
        - Annotations: UserGuide/tracks/annotations.md
        - Alignments:
            - Basics: UserGuide/tracks/alignments/viewing_alignments_basics.md
            - Paired-end alignments: UserGuide/tracks/alignments/paired_end_alignments.md
            - RNA-seq data: UserGuide/tracks/alignments/rna_seq.md
            - Methylation data: UserGuide/tracks/alignments/methylation.md
        - Variants (VCF): UserGuide/tracks/vcf.md
        - Mutations (MAF) : UserGuide/tracks/maf.md
        - Segmented copy number: UserGuide/tracks/seg.md
        - GWAS: UserGuide/tracks/gwas.md
        - RNA structure: UserGuide/tracks/rna_structure.md
    - Navigating the view: UserGuide/navigation.md
    - Sessions: UserGuide/sessions.md
    - Sample attributes: UserGuide/sample_attributes.md
    - Preferences: UserGuide/preferences.md
    - Saving images: UserGuide/saving_images.md
    - Tools Menu:
        - Batch scripts: UserGuide/tools/batch.md
        - igvtools: UserGuide/tools/igvtools_ui.md
        - Motif finder: UserGuide/tools/motif_finder.md
        - BLAT: UserGuide/tools/blat.md
        - Combining tracks: UserGuide/tools/combine_tracks.md
    - Advanced:    
      - IGV from the command line: UserGuide/advanced/command_line.md
      - External control of IGV: UserGuide/advanced/external_control.md
      - Authentication: UserGuide/advanced/oauth.md
      - Hosting genomes: UserGuide/advanced/hosting_genomes.md
    
- Tutorial Videos: http://www.youtube.com/channel/UCb5W5WqauDOwubZHb-IA_rA


- Download IGV: downloadPage.md

- Release Notes: 
    - 2.15.x: ReleaseNotes/2.15.x.md
    - 2.14.x: ReleaseNotes/2.14.x.md
    - 2.13.x: ReleaseNotes/2.13.x.md
    - 2.12.x: ReleaseNotes/2.12.x.md
    - 2.11.x: ReleaseNotes/2.11.x.md
    
- https://igv.org: https://igv.org

markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: 'Direct link to this section'
  - extra
  - sane_lists
  - wikilinks
  - admonition

extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: false
