site_name: 'IGV Desktop Application'

theme: 
  name: 'windmill'
  custom_dir: custom
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

nav:
- IGV Desktop Application: index.md

- User Guide: 
    - IGV Basics: UserGuide/IGVbasics.md
    - Reference Genome: UserGuide/reference_genome.md
    - Tracks and Data Types:
        - Numeric Data: UserGuide/tracks/numeric_data.md
        - Annotations: UserGuide/tracks/annotations.md
        - Alignments:
            - Basics: UserGuide/tracks/alignments/viewing_alignments.md
            - Insert Size: UserGuide/tracks/alignments/insert_size.md
            - Pair Orientation: UserGuide/tracks/alignments/pair_orientation.md
            - Bisulfite Sequencing: UserGuide/tracks/alignments/bisulfite.md
            - Base Modifications: UserGuide/tracks/alignments/5mc.md
            - Splice Junctions: UserGuide/tracks/alignments/splice_junctions.md
            - Sashimi Plot: UserGuide/tracks/alignments/sashimi.md
        - Variants (VCF): UserGuide/tracks/vcf.md
        - Mutations (MAF) : UserGuide/tracks/maf.md
        - Segmented Copy Number: UserGuide/tracks/seg.md
        - GWAS: UserGuide/tracks/gwas.md
        - RNA Structure: UserGuide/tracks/rna_structure.md
    - Navigating the View: UserGuide/navigation.md
    - Sessions: UserGuide/sessions.md
    - Sample Attributes: UserGuide/sample_attributes.md
    - Preferences: UserGuide/preferences.md
    - Saving Images: UserGuide/saving_images.md
    - Tools Menu:
        - Batch Scripts: UserGuide/tools/batch.md
        - igvtools: UserGuide/tools/igvtools_ui.md
        - Motif Finder: UserGuide/tools/motif_finder.md
        - BLAT: UserGuide/tools/blat.md
        - Combining Tracks: UserGuide/tools/combine_tracks.md
    - Advanced:
      - External Control of IGV: UserGuide/advanced/external_control.md
      - Command line usage: UserGuide/advanced/command_line.md
      - Authentication: UserGuide/advanced/oauth.md
      - Hosting Genomes: UserGuide/advanced/hosting_genomes.md
    
- Release Notes: 
    - 2.15.x: ReleaseNotes/2.15.x.md
    - 2.14.x: ReleaseNotes/2.14.x.md
    - 2.13.x: ReleaseNotes/2.13.x.md
    - 2.12.x: ReleaseNotes/2.12.x.md
    - 2.11.x: ReleaseNotes/2.11.x.md


markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: 'Direct link to this section'
  - extra
  - sane_lists
  - wikilinks
  - admonition

extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: false
