site_name: 'IGV Desktop Application'

theme: 
  name: 'windmill'
  custom_dir: custom
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

nav:

- About IGV: index.md
- Quick Start: QuickStart.md

- User Guide:    
    - Reference genome: UserGuide/reference_genome.md  
    - Loading and removing data: UserGuide/loading_data.md
    - Navigating the view: UserGuide/navigation.md
    - Tracks and Data Types:
        - Track attributes: UserGuide/tracks/track_attributes.md
        - Genome annotations: UserGuide/tracks/annotations.md
        - Quantitative data: UserGuide/tracks/quantitative_data.md
        - Alignments:
            - Alignments basics: UserGuide/tracks/alignments/viewing_alignments_basics.md
            - Paired-end alignments: UserGuide/tracks/alignments/paired_end_alignments.md
            - RNA-seq data: UserGuide/tracks/alignments/rna_seq.md
            - Bisulfite sequencing: UserGuide/tracks/alignments/bisulfite_sequencing.md
            - Base modifications:  UserGuide/tracks/alignments/base_modifications.md
            - SMRT kinetics:  UserGuide/tracks/alignments/smrt.md
        - Variants (VCF): UserGuide/tracks/vcf.md
        - Segmented copy number: UserGuide/tracks/seg.md
        - GWAS: UserGuide/tracks/gwas.md
        - RNA structure: UserGuide/tracks/rna_structure.md
    - Sample attributes: UserGuide/sample_attributes.md
    - Regions: UserGuide/regions.md
    - Sessions: UserGuide/sessions.md
    - Saving images: UserGuide/saving_images.md
    - User preferences: UserGuide/preferences.md
    - Tools Menu:
        - Batch scripts: UserGuide/tools/batch.md
        - igvtools: UserGuide/tools/igvtools_ui.md
        - Motif finder: UserGuide/tools/motif_finder.md
        - BLAT: UserGuide/tools/blat.md
        - Combining tracks: UserGuide/tools/combine_tracks.md
    - Advanced:    
      - IGV from the command line: UserGuide/advanced/command_line.md
      - External control of IGV: UserGuide/advanced/external_control.md
      - Hosting genomes: UserGuide/advanced/hosting_genomes.md
      - Downloading genomes: UserGuide/advanced/download_genomes.md
      - Authentication: UserGuide/advanced/oauth.md
      - AWS support:  UserGuide/advanced/aws.md
      
- File Formats: 
    - Data Tracks: FileFormats/DataTracks.md
    - Sample Info (Attributes): FileFormats/SampleInfo.md
    - Genomes: FileFormats/Genomes.md   
    
- Tutorial Videos: TutorialVideos.md


- Download: DownloadPage.md

- Release Notes: 
    - 2.16.x: ReleaseNotes/2.16.x.md 
    - 2.15.x: ReleaseNotes/2.15.x.md
    - 2.14.x: ReleaseNotes/2.14.x.md
    - 2.13.x: ReleaseNotes/2.13.x.md
    - 2.12.x: ReleaseNotes/2.12.x.md
    - 2.11.x: ReleaseNotes/2.11.x.md
    - 2.10.x: ReleaseNotes/2.10.x.md
    - 2.9.x: ReleaseNotes/2.9.x.md
    - 2.8.x: ReleaseNotes/2.8.x.md

- Getting Help: GettingHelp.md

markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: 'Direct link to this section'
  - extra
  - sane_lists
  - wikilinks
  - admonition

extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: false
