site_name: 'IGV Documentation'

theme: 
  name: 'windmill'
  custom_dir: custom
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

nav:
- Documentation Home: index.md

- igv.org: 'https://www.igv.org'
  

markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: 'Direct link to this section'
  - extra
  - sane_lists
  - wikilinks
  - admonition

extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: false
